name: tibetan_calendar
description: Tibetan Calender package provide easy way to get tibetan date and year base on western date. For more you can refer documentaion
version: 0.0.6
homepage: https://github.com/CodingWithTashi/tibetan_calendar.git
issue_tracker: https://github.com/CodingWithTashi/tibetan_calendar/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.22.1